#!/bin/bash

set -e

cd "$(dirname "$0")/../builtinFonts"

if command -v python3 >/dev/null 2>&1; then
  PYTHON_BIN=python3
elif command -v python >/dev/null 2>&1; then
  PYTHON_BIN=python
else
  echo "python3/python not found" >&2
  exit 1
fi

font_id() {
  "$PYTHON_BIN" - "$@" <<'PY'
import hashlib
import sys

total = 0
for path in sys.argv[1:]:
    with open(path, "rb") as f:
        total += int(hashlib.sha256(f.read()).hexdigest(), 16)

value = total % (2 ** 32) - (2 ** 31)
print(value)
PY
}

echo "// The contents of this file are generated by ./lib/EpdFont/scripts/build-font-ids.sh"
echo "#pragma once"
echo ""

echo "#define BOOKERLY_10_FONT_ID ($(font_id ./bookerly_10_regular.h ./bookerly_10_bold.h ./bookerly_10_bolditalic.h ./bookerly_10_italic.h))"
echo "#define BOOKERLY_12_FONT_ID ($(font_id ./bookerly_12_regular.h ./bookerly_12_bold.h ./bookerly_12_bolditalic.h ./bookerly_12_italic.h))"
echo "#define BOOKERLY_14_FONT_ID ($(font_id ./bookerly_14_regular.h ./bookerly_14_bold.h ./bookerly_14_bolditalic.h ./bookerly_14_italic.h))"
echo "#define BOOKERLY_16_FONT_ID ($(font_id ./bookerly_16_regular.h ./bookerly_16_bold.h ./bookerly_16_bolditalic.h ./bookerly_16_italic.h))"
echo "#define BOOKERLY_18_FONT_ID ($(font_id ./bookerly_18_regular.h ./bookerly_18_bold.h ./bookerly_18_bolditalic.h ./bookerly_18_italic.h))"
echo "#define LEXEND_10_FONT_ID ($(font_id ./lexend_10_regular.h ./lexend_10_bold.h ./lexend_10_regular.h ./lexend_10_bold.h))"
echo "#define LEXEND_12_FONT_ID ($(font_id ./lexend_12_regular.h ./lexend_12_bold.h ./lexend_12_regular.h ./lexend_12_bold.h))"
echo "#define LEXEND_14_FONT_ID ($(font_id ./lexend_14_regular.h ./lexend_14_bold.h ./lexend_14_regular.h ./lexend_14_bold.h))"
echo "#define LEXEND_16_FONT_ID ($(font_id ./lexend_16_regular.h ./lexend_16_bold.h ./lexend_16_regular.h ./lexend_16_bold.h))"
echo "#define LEXEND_18_FONT_ID ($(font_id ./lexend_18_regular.h ./lexend_18_bold.h ./lexend_18_regular.h ./lexend_18_bold.h))"
echo "#define NOTOSANS_10_FONT_ID ($(font_id ./notosans_10_regular.h ./notosans_10_bold.h ./notosans_10_bolditalic.h ./notosans_10_italic.h))"
echo "#define NOTOSANS_12_FONT_ID ($(font_id ./notosans_12_regular.h ./notosans_12_bold.h ./notosans_12_bolditalic.h ./notosans_12_italic.h))"
echo "#define NOTOSANS_14_FONT_ID ($(font_id ./notosans_14_regular.h ./notosans_14_bold.h ./notosans_14_bolditalic.h ./notosans_14_italic.h))"
echo "#define NOTOSANS_16_FONT_ID ($(font_id ./notosans_16_regular.h ./notosans_16_bold.h ./notosans_16_bolditalic.h ./notosans_16_italic.h))"
echo "#define NOTOSANS_18_FONT_ID ($(font_id ./notosans_18_regular.h ./notosans_18_bold.h ./notosans_18_bolditalic.h ./notosans_18_italic.h))"
echo "#define OPENDYSLEXIC_8_FONT_ID ($(font_id ./opendyslexic_8_regular.h ./opendyslexic_8_bold.h ./opendyslexic_8_bolditalic.h ./opendyslexic_8_italic.h))"
echo "#define OPENDYSLEXIC_10_FONT_ID ($(font_id ./opendyslexic_10_regular.h ./opendyslexic_10_bold.h ./opendyslexic_10_bolditalic.h ./opendyslexic_10_italic.h))"
echo "#define OPENDYSLEXIC_12_FONT_ID ($(font_id ./opendyslexic_12_regular.h ./opendyslexic_12_bold.h ./opendyslexic_12_bolditalic.h ./opendyslexic_12_italic.h))"
echo "#define OPENDYSLEXIC_14_FONT_ID ($(font_id ./opendyslexic_14_regular.h ./opendyslexic_14_bold.h ./opendyslexic_14_bolditalic.h ./opendyslexic_14_italic.h))"
echo "#define UI_10_FONT_ID ($(font_id ./ubuntu_10_regular.h ./ubuntu_10_bold.h))"
echo "#define UI_12_FONT_ID ($(font_id ./ubuntu_12_regular.h ./ubuntu_12_bold.h))"
echo "#define SMALL_FONT_ID ($(font_id ./notosans_8_regular.h))"
