#!/bin/bash

set -e

cd "$(dirname "$0")/../builtinFonts"

echo "// The contents of this file are generated by ./lib/EpdFont/scripts/build-font-ids.sh"
echo "#pragma once"
echo ""


echo "#define BOOKERLY_14_FONT_ID ($(
ruby -rdigest -e 'puts [
  "./bookerly_14_regular.h",
  "./bookerly_14_bold.h",
  "./bookerly_14_bolditalic.h",
  "./bookerly_14_italic.h",
].map{|f| Digest::SHA256.hexdigest(File.read(f)).to_i(16) }.sum % (2 ** 32) - (2 ** 31)'
))"

echo "#define BOOKERLY_16_FONT_ID ($(
ruby -rdigest -e 'puts [
  "./bookerly_16_regular.h",
  "./bookerly_16_bold.h",
  "./bookerly_16_bolditalic.h",
  "./bookerly_16_italic.h",
].map{|f| Digest::SHA256.hexdigest(File.read(f)).to_i(16) }.sum % (2 ** 32) - (2 ** 31)'
))"

echo "#define BOOKERLY_18_FONT_ID ($(
ruby -rdigest -e 'puts [
  "./bookerly_18_regular.h",
  "./bookerly_18_bold.h",
  "./bookerly_18_bolditalic.h",
  "./bookerly_18_italic.h",
].map{|f| Digest::SHA256.hexdigest(File.read(f)).to_i(16) }.sum % (2 ** 32) - (2 ** 31)'
))"

echo "#define BOOKERLY_20_FONT_ID ($(
ruby -rdigest -e 'puts [
  "./bookerly_20_regular.h",
  "./bookerly_20_bold.h",
  "./bookerly_20_bolditalic.h",
  "./bookerly_20_italic.h",
].map{|f| Digest::SHA256.hexdigest(File.read(f)).to_i(16) }.sum % (2 ** 32) - (2 ** 31)'
))"

echo "#define BOOKERLY_22_FONT_ID ($(
ruby -rdigest -e 'puts [
  "./bookerly_22_regular.h",
  "./bookerly_22_bold.h",
  "./bookerly_22_bolditalic.h",
  "./bookerly_22_italic.h",
].map{|f| Digest::SHA256.hexdigest(File.read(f)).to_i(16) }.sum % (2 ** 32) - (2 ** 31)'
))"

echo "#define LEXEND_10_FONT_ID ($(
ruby -rdigest -e 'puts [
  "./lexend_10_regular.h",
  "./lexend_10_bold.h",
].map{|f| Digest::SHA256.hexdigest(File.read(f)).to_i(16) }.sum % (2 ** 32) - (2 ** 31)'
))"

echo "#define LEXEND_12_FONT_ID ($(
ruby -rdigest -e 'puts [
  "./lexend_12_regular.h",
  "./lexend_12_bold.h",
].map{|f| Digest::SHA256.hexdigest(File.read(f)).to_i(16) }.sum % (2 ** 32) - (2 ** 31)'
))"

echo "#define LEXEND_14_FONT_ID ($(
ruby -rdigest -e 'puts [
  "./lexend_14_regular.h",
  "./lexend_14_bold.h",
].map{|f| Digest::SHA256.hexdigest(File.read(f)).to_i(16) }.sum % (2 ** 32) - (2 ** 31)'
))"

echo "#define LEXEND_16_FONT_ID ($(
ruby -rdigest -e 'puts [
  "./lexend_16_regular.h",
  "./lexend_16_bold.h",
].map{|f| Digest::SHA256.hexdigest(File.read(f)).to_i(16) }.sum % (2 ** 32) - (2 ** 31)'
))"

echo "#define LEXEND_18_FONT_ID ($(
ruby -rdigest -e 'puts [
  "./lexend_18_regular.h",
  "./lexend_18_bold.h",
].map{|f| Digest::SHA256.hexdigest(File.read(f)).to_i(16) }.sum % (2 ** 32) - (2 ** 31)'
))"

echo "#define OPENDYSLEXIC_12_FONT_ID ($(
ruby -rdigest -e 'puts [
  "./opendyslexic_12_regular.h",
  "./opendyslexic_12_bold.h",
  "./opendyslexic_12_bolditalic.h",
  "./opendyslexic_12_italic.h",
].map{|f| Digest::SHA256.hexdigest(File.read(f)).to_i(16) }.sum % (2 ** 32) - (2 ** 31)'
))"

echo "#define OPENDYSLEXIC_14_FONT_ID ($(
ruby -rdigest -e 'puts [
  "./opendyslexic_14_regular.h",
  "./opendyslexic_14_bold.h",
  "./opendyslexic_14_bolditalic.h",
  "./opendyslexic_14_italic.h",
].map{|f| Digest::SHA256.hexdigest(File.read(f)).to_i(16) }.sum % (2 ** 32) - (2 ** 31)'
))"

echo "#define OPENDYSLEXIC_16_FONT_ID ($(
ruby -rdigest -e 'puts [
  "./opendyslexic_16_regular.h",
  "./opendyslexic_16_bold.h",
  "./opendyslexic_16_bolditalic.h",
  "./opendyslexic_16_italic.h",
].map{|f| Digest::SHA256.hexdigest(File.read(f)).to_i(16) }.sum % (2 ** 32) - (2 ** 31)'
))"

echo "#define OPENDYSLEXIC_18_FONT_ID ($(
ruby -rdigest -e 'puts [
  "./opendyslexic_18_regular.h",
  "./opendyslexic_18_bold.h",
  "./opendyslexic_18_bolditalic.h",
  "./opendyslexic_18_italic.h",
].map{|f| Digest::SHA256.hexdigest(File.read(f)).to_i(16) }.sum % (2 ** 32) - (2 ** 31)'
))"

echo "#define OPENDYSLEXIC_20_FONT_ID ($(
ruby -rdigest -e 'puts [
  "./opendyslexic_20_regular.h",
  "./opendyslexic_20_bold.h",
  "./opendyslexic_20_bolditalic.h",
  "./opendyslexic_20_italic.h",
].map{|f| Digest::SHA256.hexdigest(File.read(f)).to_i(16) }.sum % (2 ** 32) - (2 ** 31)'
))"

echo "#define UI_10_FONT_ID ($(
ruby -rdigest -e 'puts [
  "./ubuntu_10_regular.h",
  "./ubuntu_10_bold.h",
].map{|f| Digest::SHA256.hexdigest(File.read(f)).to_i(16) }.sum % (2 ** 32) - (2 ** 31)'
))"

echo "#define UI_12_FONT_ID ($(
ruby -rdigest -e 'puts [
  "./ubuntu_12_regular.h",
  "./ubuntu_12_bold.h",
].map{|f| Digest::SHA256.hexdigest(File.read(f)).to_i(16) }.sum % (2 ** 32) - (2 ** 31)'
))"

echo "#define SMALL_FONT_ID ($(
ruby -rdigest -e 'puts [
  "./lexend_8_regular.h",
].map{|f| Digest::SHA256.hexdigest(File.read(f)).to_i(16) }.sum % (2 ** 32) - (2 ** 31)'
))"
