#pragma once

#include <builtinFonts/bookerly_10_bold.h>
#include <builtinFonts/bookerly_10_bolditalic.h>
#include <builtinFonts/bookerly_10_italic.h>
#include <builtinFonts/bookerly_10_regular.h>
#include <builtinFonts/bookerly_12_bold.h>
#include <builtinFonts/bookerly_12_bolditalic.h>
#include <builtinFonts/bookerly_12_italic.h>
#include <builtinFonts/bookerly_12_regular.h>
#include <builtinFonts/bookerly_14_bold.h>
#include <builtinFonts/bookerly_14_bolditalic.h>
#include <builtinFonts/bookerly_14_italic.h>
#include <builtinFonts/bookerly_14_regular.h>
#include <builtinFonts/bookerly_16_bold.h>
#include <builtinFonts/bookerly_16_bolditalic.h>
#include <builtinFonts/bookerly_16_italic.h>
#include <builtinFonts/bookerly_16_regular.h>
#include <builtinFonts/bookerly_18_bold.h>
#include <builtinFonts/bookerly_18_bolditalic.h>
#include <builtinFonts/bookerly_18_italic.h>
#include <builtinFonts/bookerly_20_regular.h>
#include <builtinFonts/bookerly_20_bold.h>
#include <builtinFonts/bookerly_20_bolditalic.h>
#include <builtinFonts/bookerly_20_italic.h>
#include <builtinFonts/bookerly_20_regular.h>
#include <builtinFonts/bookerly_22_bold.h>
#include <builtinFonts/bookerly_22_bolditalic.h>
#include <builtinFonts/bookerly_22_italic.h>
#include <builtinFonts/bookerly_22_regular.h>
#include <builtinFonts/lexend_10_bold.h>
#include <builtinFonts/lexend_10_regular.h>
#include <builtinFonts/lexend_12_bold.h>
#include <builtinFonts/lexend_12_regular.h>
#include <builtinFonts/lexend_14_bold.h>
#include <builtinFonts/lexend_14_regular.h>
#include <builtinFonts/lexend_16_bold.h>
#include <builtinFonts/lexend_16_regular.h>
#include <builtinFonts/lexend_18_bold.h>
#include <builtinFonts/lexend_18_regular.h>
#include <builtinFonts/ubuntu_8_bold.h>
#include <builtinFonts/ubuntu_8_regular.h>
#include <builtinFonts/notosans_8_regular.h>
#include <builtinFonts/notosans_10_regular.h>
#include <builtinFonts/notosans_12_bold.h>
#include <builtinFonts/notosans_12_bolditalic.h>
#include <builtinFonts/notosans_12_italic.h>
#include <builtinFonts/notosans_12_regular.h>
#include <builtinFonts/notosans_14_bold.h>
#include <builtinFonts/notosans_14_bolditalic.h>
#include <builtinFonts/notosans_14_italic.h>
#include <builtinFonts/notosans_14_regular.h>
#include <builtinFonts/notosans_16_bold.h>
#include <builtinFonts/notosans_16_bolditalic.h>
#include <builtinFonts/notosans_16_italic.h>
#include <builtinFonts/notosans_16_regular.h>
#include <builtinFonts/notosans_18_bold.h>
#include <builtinFonts/notosans_18_bolditalic.h>
#include <builtinFonts/notosans_18_italic.h>
#include <builtinFonts/notosans_18_regular.h>
#include <builtinFonts/ubuntu_10_bold.h>
#include <builtinFonts/ubuntu_10_regular.h>
#include <builtinFonts/ubuntu_12_bold.h>
#include <builtinFonts/ubuntu_12_regular.h>
