#pragma once

#ifndef CROSSPOINT_BASE_VERSION
#define CROSSPOINT_BASE_VERSION CROSSPOINT_VERSION
#endif

#ifndef VCODEX_VERSION
#define VCODEX_VERSION CROSSPOINT_VERSION
#endif

#ifndef CROSSPOINT_VERSION_CODE
#define CROSSPOINT_VERSION_CODE "dev"
#endif

#ifndef VCODEX_VERSION_CODE
#define VCODEX_VERSION_CODE CROSSPOINT_VERSION_CODE
#endif

#define CROSSPOINT_VERSION_DISPLAY "CPR " CROSSPOINT_BASE_VERSION " | vCodex " VCODEX_VERSION " | VC " VCODEX_VERSION_CODE
